title: "IA + AEC"
author: Bryan S. Cruz
logo: ""
copyright: "2026"

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution

html:
  home_page_in_navbar: true
  favicon: ""

repository:
  url: https://github.com/byama/Bryansycruz
  branch: main
  path_to_book: ""

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""
  thebe: false

sphinx:
  config:
    language: es
    html_static_path:
      - _static
    html_css_files:
      - custom.css
    html_js_files:
      - custom.js
    html_sidebars:
      "**": []
    html_theme_options:
      navigation_with_keys: true
      navbar_end:
        - search-field.html
        - navbar-icon-links.html
      secondary_sidebar_items: []
      use_download_button: false
      use_fullscreen_button: false
      show_toc_level: 0
